// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search the ad section ', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search the ad section ', async function() {
    // Test name: search the ad section 
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.njuskalo.hr/")
    // 2 | setWindowSize | 1440x790 | 
    await driver.manage().window().setRect({ width: 1440, height: 790 })
    // 3 | click | css=.BaseCategory--0 > .BaseCategory-inner | 
    await driver.findElement(By.css(".BaseCategory--0 > .BaseCategory-inner")).click()
    // 4 | click | css=.BaseCategory--2 > .BaseCategory-inner | 
    await driver.findElement(By.css(".BaseCategory--2 > .BaseCategory-inner")).click()
    // 5 | click | linkText=Autobusi | 
    await driver.findElement(By.linkText("Autobusi")).click()
  })
})
